#!/usr/bin/env bash
set -euo pipefail

# the whole body of the script is wrapped in a function so that a partially
# downloaded script does not get executed by accident. The function is called
# at the end
main () {

# Reset
Color_Off='\033[0m' # Text Reset

# Regular Colors
Red='\033[0;31m'   # Red
Green='\033[0;32m' # Green
Dim='\033[0;2m'    # White

# Bold
Bold_Green='\033[1;32m' # Bold Green
Bold_White='\033[1m'    # Bold White

error() {
    echo -e "${Red}error${Color_Off}:" "$@" >&2
    exit 1
}

info() {
    echo -e "${Dim}$* ${Color_Off}"
}

info_bold() {
    echo -e "${Bold_White}$* ${Color_Off}"
}

success() {
    echo -e "${Green}$* ${Color_Off}"
}

tildify() {
    if [[ $1 = $HOME/* ]]; then
        local replacement=\~/

        echo "${1/$HOME\//$replacement}"
    else
        echo "$1"
    fi
}

case $(uname -ms) in
'Darwin x86_64')
    target=x86_64-apple-darwin
    ;;
'Darwin arm64')
    target=aarch64-apple-darwin
    ;;
'Linux x86_64')
    target=x86_64-unknown-linux-musl
    ;;
*)
    error "The Dune Developer Preview does not currently support $(uname -ms)."
esac

today=$(date +"%Y-%m-%d")
tar_target_name="dune-$today-$target"
tar_target="$tar_target_name.tar.gz"
dune_tar_uri="https://get.dune.build/$today/$target/$tar_target"

install_dir="$HOME/.dune"
bin_dir="$install_dir/bin"
tmp_dir="$install_dir/tmp"
exe="$bin_dir/dune"
tmp_tar="$tmp_dir/$tar_target"
tmp_tar_dir="$tmp_dir/$tar_target_name"
tmp_exe="$tmp_tar_dir/dune"
tilde_bin_dir=$(tildify "$bin_dir")

command -v tar >/dev/null 2>&1 ||
    error "Failed to find tar. This script needs tar to be able to install dune."

if [[ ! -d "$bin_dir" ]]; then
    mkdir -p "$bin_dir" ||
        error "Failed to create install directory \"$bin_dir\""
fi

if [[ ! -d "$tmp_dir" ]]; then
    mkdir -p "$tmp_dir" ||
        error "Failed to create temporary directory \"$tmp_dir\""
    trap 'rm -r "$tmp_dir"' EXIT
fi

curl --fail --location --progress-bar --output "$tmp_tar" "$dune_tar_uri" ||
    error "Failed to download dune tar from \"$dune_tar_uri\""

tar -xf "$tmp_tar" -C "$tmp_dir" 2>&1 > /dev/null ||
    error "Failed to extract dune archive content from \"$tmp_tar\""

mv "$tmp_exe" "$exe" ||
    error "Failed to move executable from $tmp_exe to $exe"

rm -rf "$install_dir/env" && mv "$tmp_tar_dir/env" "$install_dir" ||
    error "Failed to move env from $tmp_tar_dir to $install_dir"

success "dune $target was installed successfully to $Bold_Green$(tildify "$exe")"

echo

case $(basename "$SHELL") in
fish)
    env_file="\$HOME/.dune/env/env.fish"

    fish_config=$HOME/.config/fish/config.fish
    tilde_fish_config=$(tildify "$fish_config")

    # deliberately omit the home directory from the pattern so "~" and "$HOME" can be used interchangeably
    if [ -f "$fish_config" ] && match=$(grep -n ".dune/env/env.fish" $fish_config); then
        echo "Shell configuration for dune appears to already exist in \"$fish_config\":"
        echo "$match"
        refresh_command="source $tilde_fish_config"
    elif [[ -w $fish_config ]]; then
        {
            echo -e '\n# dune'
            echo "source $env_file"
        } >>"$fish_config"

        info "Sourced \"$env_file\" in \"$tilde_fish_config\""

        refresh_command="source $tilde_fish_config"
    else
        echo "Manually source the file \"$env_file\""
    fi
    ;;
zsh)
    env_file="\$HOME/.dune/env/env.zsh"

    zsh_config=$HOME/.zshrc
    tilde_zsh_config=$(tildify "$zsh_config")

    # deliberately omit the home directory from the pattern so "~" and "$HOME" can be used interchangeably
    if [ -f "$zsh_config" ] && match=$(grep -n ".dune/env/env.zsh" $zsh_config); then
        echo "Shell configuration for dune appears to already exist in \"$zsh_config\":"
        echo "$match"
        refresh_command="exec $SHELL"
    elif [[ -w $zsh_config ]]; then
        {
            echo -e '\n# dune'
            echo "source $env_file"
        } >>"$zsh_config"

        info "Sourced \"$env_file\" in \"$tilde_zsh_config\""

        refresh_command="exec $SHELL"
    else
        echo "Manually source the file \"$env_file\" in \"$tilde_zsh_config\""
    fi
    ;;
bash)
    env_file="\$HOME/.dune/env/env.bash"

    bash_configs=(
        "$HOME/.bashrc"
        "$HOME/.bash_profile"
    )

    if [[ ${XDG_CONFIG_HOME:-} ]]; then
        bash_configs+=(
            "$XDG_CONFIG_HOME/.bash_profile"
            "$XDG_CONFIG_HOME/.bashrc"
            "$XDG_CONFIG_HOME/bash_profile"
            "$XDG_CONFIG_HOME/bashrc"
        )
    fi

    already_configured=false
    for bash_config in "${bash_configs[@]}"; do
        # deliberately omit the home directory from the pattern so "~" and "$HOME" can be used interchangeably
        if [ -f "$bash_config" ] && match=$(grep -n ".dune/env/env.bash" $bash_config); then
            set_manually=false
            echo "Shell configuration for dune appears to already exist in \"$bash_config\":"
            echo "$match"
            refresh_command="source $bash_config"
            already_configured=true
            break
        fi
    done
    if [ "$already_configured" = false ]; then
        set_manually=true
        for bash_config in "${bash_configs[@]}"; do
            tilde_bash_config=$(tildify "$bash_config")

            if [[ -w $bash_config ]]; then
                {
                    echo -e '\n# dune'
                    echo "source $env_file"
                } >>"$bash_config"

                info "Sourced \"$env_file\" in \"$tilde_bash_config\""

                refresh_command="source $bash_config"
                set_manually=false
                break
            fi
        done

        if [[ $set_manually = true ]]; then
            echo "Manually source the file \"$env_file\" in \"$tilde_bash_config\""
        fi
    fi
    ;;
*)
    echo 'Manually source the appropriate file in $HOME/.dune/env in your shell config (e.g. ~/.bashrc)'
    ;;
esac

echo
info "To get started, run:"
echo

if [[ $refresh_command ]]; then
    info_bold "  $refresh_command"
fi

info_bold "  dune --help"

# end of main
}

main
